package ball_race_v_003;

public enum BallColor {
    RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET,
    BLACK, WHITE, GRAY, SILVER, MAROON, OLIVE, LIME, TEAL, NAVY,
    FUCHSIA, AQUA, CORAL, WHEAT, MINT, PEACH, BEIGE, MUSTARD,
    CHARCOAL, IVORY, PLUM, ORCHID, TURQUOISE, SIENNA, CHARTREUSE, AZURE
}
